name: Build SkriBidi

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-external-template.yml
    with:
      package_name: 'skribidi'
      result_folder_name: 'SkriBidi'
      result_lib_name: 'libskribidi'
      package_version: '1e8038'
    secrets:
      dm_packages_url: ${{ secrets.DM_PACKAGES_URL }}
